In [1]:
# import matplotlib.pyplot as plt
import geopandas as gpd
import pandas as pd
import numpy as np
import requests

In [2]:
url = "https://www.mise.gov.it/images/exportCSV/prezzo_alle_8.csv"
df_prezzi = pd.read_csv(url, delimiter=';', skiprows=1)
df_prezzi.head(1)

   idImpianto descCarburante  prezzo  isSelf               dtComu
0        6492    Hi-Q Diesel   1.644       1  28/11/2022 00:33:00

In [3]:
df_prezzi[df_prezzi.idImpianto == 36320]

       idImpianto    descCarburante  prezzo  isSelf               dtComu
64507       36320           Benzina   1.749       1  15/04/2022 12:05:25
64508       36320           Gasolio   1.799       1  15/04/2022 12:05:25
64509       36320  Excellium Diesel   1.799       1  15/04/2022 12:05:25

In [5]:
df_prezzi = df_prezzi.loc[:, ['idImpianto', 'descCarburante', 'prezzo']]
df_prezzi.columns = ['id', 'gasoline_type','price']

In [6]:
url_impianti = "https://www.mise.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv"
df_impianti = pd.read_csv(url_impianti, delimiter=';', skiprows=1, on_bad_lines='skip')
df_impianti.dropna(subset=['Latitudine', 'Longitudine']).reset_index(drop=True, inplace=True)

In [7]:
geo_stations = gpd.GeoDataFrame(
    df_impianti,
    crs='EPSG:4326',
    geometry=gpd.points_from_xy(df_impianti.Longitudine, df_impianti.Latitudine)
)

In [8]:
# Keeping only usefull columns
geo_stations = geo_stations.loc[:, ['idImpianto', 'Gestore','Bandiera', 'Nome Impianto','Indirizzo', 'Comune', 'geometry']]

## Retriving only valid geometry
geo_stations= geo_stations.loc[geo_stations.geometry.is_valid,:]
geo_stations.rename(columns={'idImpianto': 'id'}, inplace=True)
# geo_stations.to_file('impianti.geojson', driver='GeoJSON')

In [11]:
# url = 'https://github.com/napo/geospatial_course_unitn/raw/master/data/istat/istat_administrative_units_generalized_2021.gpkg'
# macroregions = gpd.read_file(url,layer="macroregions")
# fix, axes= plt.subplots(1,1, figsize=(20,20))

# plt.title('Italian Station Available')

# macroregions.to_crs(epsg=4326).plot(ax=axes, color='lightblue', edgecolor='black', alpha=0.5)
# geo_stations.plot(ax=axes,
#                     color='royalblue',
#                     markersize= 1.4
#                     )

# plt.axis('off')
# plt.savefig('italian-station.png', dpi=300)
# plt.show()

In [12]:
#macroregions.to_file('municipalities.geojson', driver='GeoJSON')

In [13]:
# url = 'https://github.com/napo/geospatial_course_unitn/raw/master/data/istat/istat_administrative_units_generalized_2021.gpkg'
# macroregions = gpd.read_file(url,layer="municipalities")
# medo = macroregions.loc[macroregions.COMUNE == 'Bergamo']
# area = result['Benzina']['5']['multipolygon']
# prices = result['Benzina']['3']['price']

In [14]:
# from shapely.geometry.multipolygon import MultiPolygon
# from shapely.geometry import Point
# from shapely.geometry import shape
# Multi = MultiPolygon([shape(area)])
# res = []
# for stat in prices[0:5]:
#     stat['geometry'] = Point(shape(stat['geometry']))
#     res.append(stat)

# medo_geo = gpd.GeoDataFrame(res)
# buffer_medo = gpd.GeoDataFrame({'geometry' :Multi})
# medo_geo['color'] =['darkgreen','yellow','red','grey','grey']
# fig, axes = plt.subplots(1,1, figsize=(10,10))


# buffer_medo.plot(ax=axes)
# medo.to_crs(epsg=4326).plot(ax=axes, color='purple')
# medo_geo.plot(ax=axes, color=medo_geo.color, markersize=100)

# plt.show()

In [70]:
from src import utils
municipalities: str = "../data/municipalities.csv.zip"

municipalities_df = (
    pd.read_csv(municipalities)
    .assign(COMUNE=lambda x: x.COMUNE.apply(utils.remove_punctuations))

)

In [50]:
def _get_items( n: int):
    for iel in range(n):
        yield municipalities_df.iloc[n]

In [51]:
municipalities_df

,centroid,area_comune,buffer_1,buffer_3,buffer_5,stationsId_one,stationsId_three,stationsId_five,all_stations,COD_RIP,COD_REG,COD_PROV,COD_CM,COD_UTS,PRO_COM,PRO_COM_T,COMUNE,COMUNE_A,CC_UTS,geometry
0,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",11874;51630;52787;45515;35308,33120;32042;39964;22530;11889,40737;49699;11877;45832;6932;25285;41941;39775...,33120;32042;40737;39964;49699;22530;11877;1188...,1,1,1,201,201,1001,1001,aglie,NaN,0,MULTIPOLYGON (((404703.55819999985 5026682.654...
1,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",9902;17525;53077,3743;3844;30968;54247;13819,20694;42063;34826;45516;33813;50539,20694;42063;34826;45516;33813;50539;3743;3844;...,1,1,1,201,201,1002,1002,airasca,NaN,0,MULTIPOLYGON (((380700.9090999998 4977305.5200...
2,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",;,;,29319,29319,1,1,1,201,201,1003,1003,ala-di-stura,NaN,0,MULTIPOLYGON (((364710.85699999984 5022090.677...
3,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",52112;40943,6228;5702;25209;47815;34549,54308;42893;48734;39635;39568;53886;54295;1541...,54308;42893;6228;5702;48734;39635;25209;39568;...,1,1,1,201,201,1004,1004,albiano-divrea,NaN,0,MULTIPOLYGON (((415942.5039999997 5033304.6089...
4,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",47816;6389;54189;42563,44444;44735;9505;11859;8005;6395;47210,7872;43114;32022;44380;18604;30893;42857;11868...,7872;43114;44444;44735;9505;32022;11859;44380;...,1,1,1,201,201,1006,1006,almese,NaN,0,MULTIPOLYGON (((376934.96169999987 4999073.853...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",;,51385;13608;45627,54457;8278;51418;39421,51385;54457;8278;51418;13608;45627;39421,1,1,3,0,3,3012,3012,barengo,NaN,0,MULTIPOLYGON (((463750.5554999998 5049455.4955...
399,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",52749;30044;41511;47331;9226,44915;45627;45637;22500;39209;20076;46045,9743;9744;21956;13608;7787,9743;9744;44915;21956;13608;45627;45637;22500;...,1,1,3,0,3,3016,3016,bellinzago-novarese,NaN,0,MULTIPOLYGON (((476111.33380000014 5047065.006...
400,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",40401;52241;38680,;,44557;17453;31509;32432;52978,44557;17453;31509;32432;52978,1,1,3,0,3,3018,3018,biandrate,NaN,0,MULTIPOLYGON (((456987.29360000044 5035042.101...
401,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",51115,29422;11745;51377;31441;33169;51824;25502,47652;49672;11750;7244;16377;49148;35221;6422;...,29422;47652;49672;11750;11745;51377;7244;16377...,1,1,3,0,3,3019,3019,boca,NaN,0,MULTIPOLYGON (((453399.97279999964 5060531.412...
402,"[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...","[{""type"": ""Feature"", ""properties"": {}, ""geomet...",47154,49672;41123;40495;39421,38920;9546;29422;51377;7244;16377;49148;31441;...,38920;9546;29422;49672;51377;7244;16377;49148;...,1,1,3,0,3,3021,3021,bogogno,NaN,0,MULTIPOLYGON (((463701.3661000002 5058639.9273...

In [46]:
m = _get_items(10)

In [56]:
for i in m:
    print(i)
    break

centroid            [{"type": "Feature", "properties": {}, "geomet...
area_comune         [{"type": "Feature", "properties": {}, "geomet...
buffer_1            [{"type": "Feature", "properties": {}, "geomet...
buffer_3            [{"type": "Feature", "properties": {}, "geomet...
buffer_5            [{"type": "Feature", "properties": {}, "geomet...
stationsId_one                                                      ;
stationsId_three                                    50324;32456;47312
stationsId_five     6794;43325;47145;37603;11888;37172;51095;37910...
all_stations        50324;6794;43325;32456;47312;47145;37603;11888...
COD_RIP                                                             1
COD_REG                                                             1
COD_PROV                                                            1
COD_CM                                                            201
COD_UTS                                                           201
PRO_COM                                                          1012
PRO_COM_T                                                        1012
COMUNE                                                       arignano
COMUNE_A                                                          NaN
CC_UTS                                                              0
geometry            MULTIPOLYGON (((413545.5007999996 4990368.9298...
Name: 10, dtype: object

In [57]:
set(i.stationsId_one.split(";")) set(i.stationsId_three.split(";"))

{'', '32456', '47312', '50324'}

In [61]:
set(i.stationsId_one.split(";")).intersection(set(i.stationsId_three.split(";")))

set()

In [77]:
print(set(municipalities_df.loc[municipalities_df.COMUNE == 'medolago'].all_stations.values[0].split(";")))

{'46031', '16552', '50176', '54900', '4644', '36320', '11306', '54373', '11253', '48550', '54369', '25303', '51452', '33398', '50286', '26246', '25733', '43387', '36373', '39057', '38229', '15311', '11431', '15828'}